name: Deploy Bot

on:
  repository_dispatch:
    types: 
      - deploy-v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar ao Servidor via SSH e fazer Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            "${{ github.event.client_payload.tag }}"
            "${{ secrets.ENV_FILE }}"
